#!/bin/bash

# Use the CI/CD variables, if they are not set, default to what's currently in the .env.template
DATABASE_USER=${CI_DATABASE_USER}
DATABASE_PASSWORD=${CI_DATABASE_PASSWORD}
DATABASE_CLUSTER=${CI_DATABASE_CLUSTER}
DATABASE_NAME=${CI_DATABASE_NAME}
CLIENT_PORT=${CI_CLIENT_PORT}
SERVER_PORT=${CI_SERVER_PORT}
WORKER_PORT=${CI_WORKER_PORT}

# Now writes these values into new .env file
cat <<EOL > .env
DATABASE_USER=$DATABASE_USER
DATABASE_PASSWORD=$DATABASE_PASSWORD
DATABASE_CLUSTER=$DATABASE_CLUSTER
DATABASE_NAME=$DATABASE_NAME
CLIENT_PORT=$CLIENT_PORT
SERVER_PORT=$SERVER_PORT
WORKER_PORT=$WORKER_PORT

EOL

# Print out the .env file (optional, for debugging purposes)
cat .env
